complete -c m2ex -f
complete -c m2ex -n __fish_use_subcommand -a check -d 'Compare installed M2EX with the latest GitHub test release'
complete -c m2ex -n __fish_use_subcommand -a update -d 'Install the latest GitHub test release'
complete -c m2ex -n __fish_use_subcommand -a status -d 'Show install path, version, and 4700 wrap state'
complete -c m2ex -n __fish_use_subcommand -a hook -d 'Wrap Medieval II (app 4700) and remove the old non-Steam shortcut'
complete -c m2ex -n __fish_use_subcommand -a uninstall -d 'Remove M2EX.exe and the 4700 launch-option wrap'
complete -c m2ex -n __fish_use_subcommand -a launch -d 'Start Medieval II through Steam'
complete -c m2ex -n __fish_use_subcommand -a help -d 'Show help'
complete -c m2ex -n '__fish_seen_subcommand_from update' -l force -d 'Reinstall even if the tag matches'
complete -c m2ex -n '__fish_seen_subcommand_from uninstall' -l yes -d 'Skip the confirmation prompt'
complete -c m2ex -n '__fish_seen_subcommand_from launch' -a 'vanilla americas britannia crusades teutonic'
