---
- name: install tmux
  apt:
    name:
      - tmux
      - xsel
    state: present
  become: true

- name: install tmuxinator
  command: gem install tmuxinator creates=/usr/local/bin/tmuxinator
  become: true

- name: install .tmux from Gregory Pakosz's oh-my-tmux
  git:
    repo: "https://github.com/gpakosz/.tmux.git"
    dest: ~/.tmux

- name: ensure .config/tmux directory exists
  file: name=~/.config/tmux state=directory mode=0700

- name: symlink that .tmux.conf
  file: src=~/.tmux/.tmux.conf dest=~/.config/tmux/tmux.conf state=link

- name: copy that .tmux.conf.local (is also managed by chezmoi)
  copy: src=~/.tmux/.tmux.conf.local dest=~/.config/tmux/tmux.conf.local force=true backup=yes

- name: install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    force: true
