---
- name: install tmux
  apt:
    name:
      - tmux
      - xsel
    state: present
  become: true

# config files are handled by chezmoi
- name: install tmuxinator
  command: gem install tmuxinator creates=/usr/local/bin/tmuxinator
  become: true

# config files are handled by chezmoi
- name: install .tmux
  git:
    repo: "https://github.com/gpakosz/.tmux.git"
    dest: ~/.tmux

- name: install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    force: true
