---
- name: ensure .ssh directory exists as prerequisite
  file: name=~/.ssh state=directory mode=0700

# config files for fish are handled by chezmoi
- name: install fish
  apt:
    name: fish
    state: present
  become: true

- name: install Starship prompt
  shell: curl -sS https://starship.rs/install.sh | sh -s -- --yes

# else install omf will fail
- name: run fish for the first time
  command: fish -c "echo first"

- name: get oh-my-fish (this is obsolete)
  get_url:
    url: https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install
    dest: /tmp/install-omf
    mode: 0755

- name: install omf (deprecated)
  command: /tmp/install-omf --noninteractive creates=~/.config/fish/conf.d/omf.fish

- name: install fish/omf nvm support (deprecated)
  command: fish -c "omf install nvm" creates=~/.local/share/omf/pkg/nvm/init.fish
