#!/bin/bash
# $1 is the final point size (Omarchy mapping plus offset).
pt=${1:-}
[[ $pt =~ ^[0-9]+$ ]] || exit 0
[[ -f ~/.config/foot/foot.ini ]] || exit 0
sed -i -E "s/(:size=)[0-9.]+/\1$pt/" ~/.config/foot/foot.ini
