# Inserts a blank line between shell prompts
add_newline = false

# Improve format
format = """
$shlvl\
$directory\
$vcsh\
$git_branch\
$docker_context\
$elm\
$helm\
$nim\
$python\
$nix_shell\
$conda\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$shell\
$character"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[env_var.STAGE]
default = "unknown"
format = "deploying to [$env_value]($style)/"

[env_var.ENV]
default = "unknown"
format = "[$env_value]($style) "
