[Theme]
Current=omarchy

[General]
DisplayServer=wayland
GreeterEnvironment=

[Wayland]
CompositorCommand=start-hyprland -- --config /usr/share/sddm/hyprland.lua

[Autologin]
Relogin=false
Session=
User=
