---
- name: install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{nvm_version}}/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: install node {{node_version}}
  shell: bash -c ". {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{node_version}}" creates="{{ ansible_env.HOME }}/.nvm/versions/node/v{{node_version}}/bin/node"

# not sure this works when updating
- name: switch to default node version
  shell: bash -c ". {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm alias default {{node_version}} && nvm use default"

- name: install yarn
  npm:
    name: yarn
    global: true
    state: present
  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_version }}/bin:{{ ansible_env.PATH }}"

- name: install pnpm
  npm:
    name: pnpm
    global: true
    state: present
  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_version }}/bin:{{ ansible_env.PATH }}"

- name: install intelephense
  npm:
    name: intelephense
    global: true
    state: present
  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_version }}/bin:{{ ansible_env.PATH }}"

- name: install typescript
  npm:
    name: typescript
    global: true
    state: present
  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_version }}/bin:{{ ansible_env.PATH }}"

- name: install typescript-language-server
  npm:
    name: typescript-language-server
    global: true
    state: present
  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_version }}/bin:{{ ansible_env.PATH }}"

- name: install claude-code
  npm:
    name: "@anthropic-ai/claude-code"
    global: true
    state: present
  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_version }}/bin:{{ ansible_env.PATH }}"

- name: install opencode
  npm:
    name: "opencode-ai@latest"
    global: true
    state: present
  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_version }}/bin:{{ ansible_env.PATH }}"
