---

- name: install dependencies to compile emacs
  apt:
    name:
      - gnutls-dev
      - aspell
      - aspell-en
      - ncurses-dev
      - libgccjit-{{libgccjit_version}}-dev # must match gcc version
      - libsystemd-dev
      - libjansson-dev
      - texinfo
      - libtree-sitter-dev
      - libdbus-1-dev
      - libxml2-dev
      - libgpm-dev
    state: present
  become: true

- name: get Emacs {{emacs_version}}
  unarchive:
    src: "https://ftp.gnu.org/gnu/emacs/emacs-{{emacs_version}}.tar.xz"
    dest: "~/src/emacs/"
    remote_src: true
    creates: ~/src/emacs/emacs-{{emacs_version}}/configure

- name: configure Emacs
  command:
    cmd: "./configure --without-x --with-native-compilation --with-json --with-tree-sitter"
    chdir: ~/src/emacs/emacs-{{emacs_version}}
    creates: ~/src/emacs/emacs-{{emacs_version}}/src/emacs

- name: make Emacs (takes a while)
  command:
    cmd: "make"
    chdir: ~/src/emacs/emacs-{{emacs_version}}
    creates: ~/src/emacs/emacs-{{emacs_version}}/src/emacs

- name: install Emacs
  command:
    cmd: "make install"
    chdir: "{{ansible_user_dir}}/src/emacs/emacs-{{emacs_version}}"
    creates: "/usr/local/bin/emacs-{{emacs_version}}"
  become: true

- name: check if ~/.emacs.d exists and is a directory
  stat:
    path: "~/.emacs.d"
  register: emacs_dir_stat

- name: move existing ~/.emacs.d to a backup if it’s a directory
  command:
    cmd: "mv ~/.emacs.d ~/.emacs.d.bak"
  when: emacs_dir_stat.stat.exists and emacs_dir_stat.stat.isdir

- name: ensure ~/.emacs.d is a symlink to ~/src/emacs
  file:
    src: "~/src/emacs"
    dest: "~/.emacs.d"
    state: link
    force: yes
