# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Insert a blank line between shell prompts
add_newline = false

# Customise format
format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$php\
$nodejs\
$elm\
$helm\
$nim\
$python\
$nix_shell\
$conda\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$shell\
$character"""

# [username]
# show_always = true
# format = "[$user]($style)@"

# [hostname]
# ssh_only = false

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[❯](bold red)"

# for docs see: https://starship.rs/config/
