# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Improve format
format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$vcsh\
$git_branch\
$docker_context\
$elm\
$helm\
$nim\
$python\
$nix_shell\
$conda\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$shell\
$character"""

[username]
show_always = true
format = "[$user]($style)@"

[hostname]
ssh_only = false

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[❯](bold red)"
